<a href="https://colab.research.google.com/github/joel8716/HelloWorld/blob/master/DSTN07_Numpy_Parte_I_COMPLETO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Agenda

> Data: 16/09/2020<br>
> Aula: 03 <br>
> Módulo: 00 <br>
> Instrutores: Bruno Vieira e Maurício Nascimento<br>
> Turma: DSTN07

O objetivo dessa aula é introduzir a biblioteca Numpy.


**Tópicos**:
* Numpy:
 - ndarray
 - Inicialização de Arrays Numpy e Primeiros Passos
 - Manipulação das dimensões de um array
 - Fatiamento em Arrays




# Numpy (Parte I)

## ndarray

O uso de arrays numpy se popularizou no meio da computação científica, por sua eficiência. Essa eficiência se deve muito em função das seguintes características:

* Todos os elementos são do mesmo tipo (float ou int)
* Os arrays têm tamanho fixo

## Inicialização de Arrays Numpy e Primeiros Passos

In [ ]:
import numpy as np

In [ ]:
# posso iniciar com uma lista
lista = [1,2,3]
# podemos definir o tipo
np_array = np.array(lista, float) 

In [ ]:
print(np_array)

[1 2 3]


In [ ]:
# Alguns atributos
# tipo
type(np_array)

numpy.ndarray

In [ ]:
# numero de dimensoes
np_array.ndim

1

In [ ]:
# shape
np_array.shape

(3,)

In [ ]:
# tamanho (numero de elementos)
np_array.size

3

In [ ]:
# Arrays de 1 e 0
# zeros
z = np.zeros((2,3))
# uns
u = np.ones((3,3), int)
i = np.identity(2,float)

In [ ]:
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
z.shape

(2, 3)

In [ ]:
z.ndim

2

In [ ]:
print(u)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
print(i)

[[1. 0.]
 [0. 1.]]


Se quisermos um array com um valor específico, usamos o ```np.full```

In [ ]:
np.full((2,3), 0.7)

array([[0.7, 0.7, 0.7],
       [0.7, 0.7, 0.7]])

## Manipulação das dimensões de um array

Se temos um array de dimensões n x m, podemos aplicar uma reformatação, para que mude suas dimensões sem alterar os dados.
O importante é que o produto n.m seja constante.



In [ ]:
# 
narray = np.full((2,6),0.45)

In [ ]:
n = 2
m = 6

In [ ]:
produto = 2*6
print(produto)

12


possibilidades:
- 3*4
- 6*2
- 4*3
- 1*12

In [ ]:
narray.reshape(3,4)

array([[0.45, 0.45, 0.45, 0.45],
       [0.45, 0.45, 0.45, 0.45],
       [0.45, 0.45, 0.45, 0.45]])

In [ ]:
narray.reshape(2,6)

In [ ]:
narray.reshape(12,1)

In [ ]:
narray.reshape(1,12)

array([[0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45,
        0.45]])

O comando ravel distorce o array multidimensional e o transforma em um array 1D.

In [ ]:
# ravel
narray = np.full((2,6),0.45)


In [ ]:
narray.ravel()

array([0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45,
       0.45])

## Fatiamento em Arrays

: --> significa todos

In [ ]:
lista = [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

In [ ]:
mat = np.array(lista)

In [ ]:
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
mat[0,0]

0

In [ ]:
mat[0,:]

array([0, 1, 2, 3])

In [ ]:
mat[:,0]

array([0, 4, 8])

In [ ]:
mat[:,2]

array([ 2,  6, 10])

Exercício, print elemento por elemento, utilizando For loop, o seguinte array: <br>
    array_exercicio = np.array([1,2,3],[4,5,6])