<a href="https://colab.research.google.com/github/joel8716/HelloWorld/blob/master/DSTN07_Numpy_Parte_II_%26_Pandas_Parte_I_COMPLETOipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Agenda

> Data: 18/09/2020<br>
> Aula: 04 <br>
> Módulo: 00 <br>
> Instrutores: Bruno Vieira e Maurício Nascimento<br>
> Turma: DSTN07

O objetivo dessa aula é introduzir a biblioteca Numpy.


**Tópicos**:
* Numpy:
 - Funções básicas (np.mean, np.std, np.linspace, np.arange, np.random.choice, np.random.int, np.random.rand, np.where)
 - Concatenação de Arrays
 - Operações entre Arrays
* Pandas:
 - Series vs Numpy Arrays
 - Inicialização de Series
 - Operações Básicas com Series
 - Concatenação de Series

In [ ]:
import numpy as np
import pandas as pd

# Numpy (Parte II)

## Funções Básicas

O Numpy possui algumas funções e submódulos que auxiliam o dia a dia do cientista.

In [ ]:
# Média
np.mean([1,2,3,4])

2.5

In [ ]:
# Desvio Padrão
np.std([1,2,3,4])

1.118033988749895

O np.arange cria um vetor espaçado entre dois números.

In [ ]:
# np.arange
np.arange(start=1, stop=20, step=2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

np.linspace gera um array de n números entre dois valores.

In [ ]:
# np.linspace
np.linspace(start=1, stop=10, num=50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
# np.where 
x = np.arange(9).reshape(3, 3)
x


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.where( x > 2 )

(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))

In [ ]:
x[np.where(x>2)]

array([3, 4, 5, 6, 7, 8])

O submódulo random do numpy pode ser utilizado para gerar números aleatórios, selecionar e embaralhar números.

In [ ]:
# escolha aleatória
np.random.choice([1,2,3,4,5], 10)

array([5, 3, 2, 4, 2, 2, 3, 3, 5, 4])

In [ ]:
# embaralhamento
x = [1,2,3]
np.random.shuffle(x)

In [ ]:
x

[3, 1, 2]

## Concatenação Arrays

Podemos unir 2 ou mais arrays, lateralmente ou verticalmente.

In [ ]:
array = np.arange(9)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array2D_1 = array.reshape((3,3))
array2D_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
array2D_2 = np.arange(10,19).reshape(3,3)

In [ ]:
# concatenação vertical
np.concatenate((array2D_1, array2D_2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
# concatenação horizontal
np.concatenate((array2D_1,array2D_2),axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [ ]:
# E como concatenar mais de 2 arrays
np.concatenate((array2D_1, array2D_2, array2D_1, array2D_1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [ ]:
array2D_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.concatenate((array2D_1, np.arange(4).reshape(2,2)))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

## Operaçõe entre Arrays

In [ ]:
array1 = np.arange(9)
array2 = np.arange(9)

In [ ]:
# Soma
array1 + array2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
# Subtração
array1 - array2

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Divisão
array1/array2

<ipython-input-57-f19415e7128b>:2: RuntimeWarning: invalid value encountered in true_divide
  array1/array2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Multiplicação
array1*array2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

E se tentarmos fazer operações com listas???

In [ ]:
[1,2,3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [ ]:
[1,2,3]*[4, 5, 6]

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
[1,2,3]/[4, 5, 6]

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [ ]:
[1,2,3]-[4, 5, 6]

TypeError: unsupported operand type(s) for -: 'list' and 'list'

# Pandas (Parte I)

A Series é o objeto base do Pandas, assim como o array é o do numpy.

* Três estruturas importantes:
    + `Series`
    + `DataFrame`
    + `Index`

## Series vs Numpy

* Visualização
* Índice

In [ ]:
# Visualização
# Numpy
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
# Visualização
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

Numpy nos traz um formato horizontal (1D). As Series são Colunas.

* **Índice**

No Numpy os arrays possuem índices numéricos (0, 1, 2, 3). No Pandas os índices podem ser numéricos e também strings.



In [ ]:
series_exemplo = pd.Series([1,2,3,4], index=['numero_1', 'numero_2', 'numero_3', 'numero_4'])

In [ ]:
series_exemplo

numero_1    1
numero_2    2
numero_3    3
numero_4    4
dtype: int64

Podemos acessar o dado como fazíamos nas listas e arrays, por meio do índice.

In [ ]:
series_exemplo[0]

1

In [ ]:
series_exemplo['numero_1']

1

In [ ]:
series_exemplo['numero_1':'numero_3']

numero_1    1
numero_2    2
numero_3    3
dtype: int64

In [ ]:
series_exemplo[0:3]

numero_1    1
numero_2    2
numero_3    3
dtype: int64

Podemos acessar seus valores



In [ ]:
series_exemplo.values

array([1, 2, 3, 4])

Podemos acessar seus índices

In [ ]:
series_exemplo.index

Index(['numero_1', 'numero_2', 'numero_3', 'numero_4'], dtype='object')

## Inicialização de Series

* Podemos construir `Series` partindo do zero. A forma geral de fazer isso é a seguinte:

```python
pd.Series(data, index = index)
```
* `index` é um argumento opcional e `data` pode ser várias coisas

In [ ]:
# Series com um único valor
pd.Series(5, index = [1, 2, 6]) 

1    5
2    5
6    5
dtype: int64

In [ ]:
# Dicionário
pd.Series({2 : 'a', 1 : 'b', 3 : 'c'}) 

2    a
1    b
3    c
dtype: object

## Operações Básicas Com Series

In [ ]:
series1 = pd.Series([1,2,3], index=['carne', 'carneiro', 'ovelha'])
series2 = pd.Series([1,2,3], index=['ovo', 'carneiro', 'ovelha'])

In [ ]:
# Soma
series1 + series2

carne       NaN
carneiro    4.0
ovelha      6.0
ovo         NaN
dtype: float64

In [ ]:
# Divisão
series1/series2

carne       NaN
carneiro    1.0
ovelha      1.0
ovo         NaN
dtype: float64

In [ ]:
# Subtração
series1 - series2

carne       NaN
carneiro    0.0
ovelha      0.0
ovo         NaN
dtype: float64

In [ ]:
# Multiplicação
series1*series2

carne       NaN
carneiro    4.0
ovelha      9.0
ovo         NaN
dtype: float64

O que é NaN ?

Todas as operações são baseadas nos índices.

In [ ]:
# filtros
series1 > 3

carne       False
carneiro    False
ovelha      False
digital      True
cabra        True
dtype: bool

o Filtro é como se estivéssemos comparando elemento por elemento e fazendo a comparação desejada.

In [ ]:
# se quisermos conhecer os valores
series1[series1 > 3]

digital    23
cabra      10
dtype: int64

In [ ]:
series1

carne        1
carneiro     2
ovelha       3
digital     23
cabra       10
dtype: int64

In [ ]:
# Se quisermos a negação da condição
series1[~(series1>2)]

carne       1
carneiro    2
dtype: int64

O que ganhamos em relação aos dicionários?

In [ ]:
series1.sum()

29

In [ ]:
series1.std()

10.53169818531972

In [ ]:
series1.max()

23

In [ ]:
series1.min()

1

E se quisermos criar um novo elemento com um novo índice?

In [ ]:
series1['cabra'] = 10

In [ ]:
series1

carne        1
carneiro     2
ovelha       3
digital     23
cabra       10
dtype: int64

In [ ]:
series2

ovo         1
carneiro    2
ovelha      3
dtype: int64

In [ ]:
# value counts
series1.value_counts()

23    1
10    1
3     1
2     1
1     1
dtype: int64

Podemos checar se o valor de uma series existe em outra series ou lista.

In [ ]:
#isin
#
series1.isin(series2)

carne        True
carneiro     True
ovelha       True
digital     False
cabra       False
dtype: bool

In [ ]:
# operador 
series1

carne        1
carneiro     2
ovelha       3
digital     23
cabra       10
dtype: int64

In [ ]:
series2

ovo         1
carneiro    2
ovelha      3
dtype: int64

## Concatenação de Series

In [ ]:
series1 

carne        1
carneiro     2
ovelha       3
digital     23
cabra       10
dtype: int64

In [ ]:
series2

ovo         1
carneiro    2
ovelha      3
dtype: int64

In [ ]:
pd.concat([series1,series2], axis=1)

0    1
carne      1.0  NaN
carneiro   2.0  2.0
ovelha     3.0  3.0
digital   23.0  NaN
cabra     10.0  NaN
ovo        NaN  1.0

In [ ]:
pd.concat([series1,series2], axis=0)

carne        1
carneiro     2
ovelha       3
digital     23
cabra       10
ovo          1
carneiro     2
ovelha       3
dtype: int64

# Exercício:

In [ ]:
import pandas as pd

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

Trazer como 2 series os valores que estão em ser1 e não estão em ser2 e vice-versa.

In [ ]:
ser1[~(ser1.isin(ser2))]

0    1
1    2
2    3
dtype: int64